  CREATE TABLE "AIRPORT" 
   (	"AIRPORT_CODE" VARCHAR2(5), 
	"NAME" VARCHAR2(100), 
	"CITY" VARCHAR2(50), 
	"COUNTRY" VARCHAR2(50), 
	 PRIMARY KEY ("AIRPORT_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CREW_DETAILS" 
   (	"CREW_ID" VARCHAR2(10), 
	"CREW_NAME" VARCHAR2(50), 
	"GENDER" VARCHAR2(10), 
	"JOB" VARCHAR2(50), 
	"HIREDATE" DATE, 
	"SAL" NUMBER, 
	"COMM" NUMBER, 
	 PRIMARY KEY ("CREW_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DETAILS_CANCEL" 
   (	"CANCEL_ID" NUMBER, 
	"PASSENGER_ID" NUMBER, 
	"PASSENGER_NAME" VARCHAR2(50), 
	"CANCEL_DATE" DATE, 
	 PRIMARY KEY ("CANCEL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "FLIGHT_DETAILS" 
   (	"FLIGHT_NO" VARCHAR2(10), 
	"FLIGHT_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"ORIGIN" VARCHAR2(30) NOT NULL ENABLE, 
	"DESTINATION" VARCHAR2(30) NOT NULL ENABLE, 
	"DEPARTURE_DATE" DATE, 
	"DEPARTURE_TIME" TIMESTAMP (6), 
	"ARRIVAL_TIME" TIMESTAMP (6), 
	"TOTAL_DISTANCE" NUMBER, 
	"FLIGHT_DURATION" NUMBER, 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("FLIGHT_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "LUGGAGE" 
   (	"LUGGAGE_ID" NUMBER, 
	"PASSENGER_ID" NUMBER, 
	"WEIGHT_KG" NUMBER, 
	"DESCRIPTION" VARCHAR2(200), 
	 PRIMARY KEY ("LUGGAGE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PASSENGER_DETAILS" 
   (	"ID_PASS" NUMBER, 
	"FLIGHT_NO" VARCHAR2(10), 
	"PASSENGER_NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"PHONE" VARCHAR2(15), 
	"GENDER" VARCHAR2(10), 
	"BOOKING_DATE" DATE, 
	 PRIMARY KEY ("ID_PASS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PASSENGER_FEEDBACK" 
   (	"FEEDBACK_ID" NUMBER, 
	"PASSENGER_ID" NUMBER, 
	"FEEDBACK" VARCHAR2(200), 
	"FEEDBACK_DATE" DATE, 
	 PRIMARY KEY ("FEEDBACK_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PASSENGER_PREFERENCES" 
   (	"PREFERENCE_ID" NUMBER, 
	"PASSENGER_ID" NUMBER, 
	"SEAT_PREFERENCE" VARCHAR2(20), 
	"MEAL_PREFERENCE" VARCHAR2(50), 
	"SPECIAL_ASSISTANCE_NEEDED" VARCHAR2(100), 
	 PRIMARY KEY ("PREFERENCE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENT_METHODS" 
   (	"PAYMENT_METHOD_ID" NUMBER, 
	"PASSENGER_ID" NUMBER, 
	"METHOD_TYPE" VARCHAR2(50), 
	"CARD_NUMBER" VARCHAR2(30), 
	"EXPIRATION_DATE" DATE, 
	"BILLING_ADDRESS" VARCHAR2(200), 
	 PRIMARY KEY ("PAYMENT_METHOD_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SEAT_ALLOTED" 
   (	"ID" NUMBER, 
	"FLIGHT_NO" VARCHAR2(10), 
	"PASSENGER_ID" NUMBER, 
	"CLASS" VARCHAR2(20), 
	"TOTAL_SEATS" NUMBER, 
	"TOTAL_PRICE" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SEAT_STATUS" 
   (	"ID" NUMBER, 
	"FLIGHT_NO" VARCHAR2(10), 
	"BUSINESS_CLASS" NUMBER, 
	"ECONOMY_CLASS" NUMBER, 
	"BUSINESS_CLASS_PRICE" NUMBER, 
	"ECONOMY_CLASS_PRICE" NUMBER, 
	"TOTAL_SEATS" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "VIP_PASSENGERS" 
   (	"VIP_ID" NUMBER, 
	"FLIGHT_NO" VARCHAR2(10), 
	"PASSENGER_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"PRIVILEGES" VARCHAR2(200), 
	 PRIMARY KEY ("VIP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHECKAIRPORTCOUNTRY" 
BEFORE INSERT OR UPDATE ON airport
FOR EACH ROW
BEGIN
    IF UPPER(:NEW.country) <> 'INDIA' THEN
        RAISE_APPLICATION_ERROR(-20002, 'Only Indian airports allowed');
    END IF;
END;
/
ALTER TRIGGER "CHECKAIRPORTCOUNTRY" ENABLE;

  ALTER TABLE "LUGGAGE" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CHECKLUGGAGEWEIGHT" 
BEFORE INSERT OR UPDATE ON luggage
FOR EACH ROW
BEGIN
    IF :NEW.weight_kg > 20 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Luggage cannot exceed 20 kg');
    END IF;
END;
/
ALTER TRIGGER "CHECKLUGGAGEWEIGHT" ENABLE;

  ALTER TABLE "PASSENGER_DETAILS" ADD FOREIGN KEY ("FLIGHT_NO")
	  REFERENCES "FLIGHT_DETAILS" ("FLIGHT_NO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRIG_DETAILS" 
AFTER DELETE ON passenger_details
FOR EACH ROW
BEGIN
    INSERT INTO details_cancel (
        cancel_id,
        passenger_id,
        passenger_name,
        cancel_date
    )
    VALUES (
        details_cancel_seq.NEXTVAL,
        :OLD.id_pass,
        :OLD.passenger_name,
        SYSDATE
    );
END;
/
ALTER TRIGGER "TRIG_DETAILS" ENABLE;

  ALTER TABLE "PASSENGER_FEEDBACK" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;

  ALTER TABLE "PASSENGER_PREFERENCES" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;

  ALTER TABLE "PAYMENT_METHODS" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;

  ALTER TABLE "SEAT_ALLOTED" ADD FOREIGN KEY ("FLIGHT_NO")
	  REFERENCES "FLIGHT_DETAILS" ("FLIGHT_NO") ENABLE;
  ALTER TABLE "SEAT_ALLOTED" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;

  ALTER TABLE "SEAT_STATUS" ADD FOREIGN KEY ("FLIGHT_NO")
	  REFERENCES "FLIGHT_DETAILS" ("FLIGHT_NO") ENABLE;

  ALTER TABLE "VIP_PASSENGERS" ADD FOREIGN KEY ("FLIGHT_NO")
	  REFERENCES "FLIGHT_DETAILS" ("FLIGHT_NO") ENABLE;
  ALTER TABLE "VIP_PASSENGERS" ADD FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "PASSENGER_DETAILS" ("ID_PASS") ENABLE;